### ISSUE TITLE
Revamped TextTrack functionality

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1655]
Going to create a new mega issue with a task list for caption and [text track related functionality](https://github.com/videojs/video.js/issues/1054) in a task list form.

* [x] Native Captions, HTML5 Tech only - #1656 
  * [x] How to add a track from a remote url -- HTML expects a new track element added
  * [x] Add [`Player#textTracks`](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-texttracks), just proxy the call
  * [x] Add [`Player#addTextTrack`](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-addtexttrack), just proxy the call
  * [x] Update captions menu to display the selected text track by setting the [texttrack mode](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-texttrack-mode) to `"showing"`
* [x] Non-Native captions, Flash, HLS, HTML (if no native captions support)
  * [x] How to add a track from a remote url
  * [x] Parse out the vtt files into a `TextTrack`s. [Maybe with vtt.js](https://github.com/videojs/video.js/issues/1044).
  * [x] Have local shims for, again, maybe via `vtt.js`:
    * [x] [TextTrackList](https://html.spec.whatwg.org/multipage/embedded-content.html#texttracklist)
    * [x] [TextTrack](https://html.spec.whatwg.org/multipage/embedded-content.html#texttrack)
    * [x] [TextTrackCueList](https://html.spec.whatwg.org/multipage/embedded-content.html#texttrackcuelist)
    * [x] [TextTrackCue](https://html.spec.whatwg.org/multipage/embedded-content.html#texttrackcue)
    * [x] [VTTCue](http://dev.w3.org/html5/webvtt/#the-vttcue-interface) (a subclass of TextTrackCue).
  * [x] Update the displayed captions with the `activeCues`. Perhaps as a [`timeupdate`](https://github.com/mozilla/vtt.js/issues/331) listener.
* [x] Figure out ads and playing different videos
* [x] Done with text tracks

[WebVTT Spec](http://dev.w3.org/html5/webvtt/)
[Track Element Spec](https://html.spec.whatwg.org/multipage/embedded-content.html#the-track-element)
[Timed Text Tracks Spec](https://html.spec.whatwg.org/multipage/embedded-content.html#timed-text-tracks)

**Comment by mmcc** [comment]
#1749 is now the latest PR.

**Comment by heff** [comment]
What's left in this one, and can it be tracked in the open PR so it's all in one place?

**Comment by gkatsev** [comment]
The things that are left: #1749 (some left over comments) and #1784.

**Comment by gkatsev** [comment]
All that's left is to merge and release, I believe!

**Comment by gkatsev** [comment]
vttjs has merged https://github.com/mozilla/vtt.js/pull/337 in. Waiting for the second PR which adds the vttjs object exporting.

**Comment by gkatsev** [comment]
Fixed via 4e5c28cc561487ff29394d19dce3a420675e4f9d
