### ISSUE TITLE
videojs 5.1 release proposal

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2742]
Trying something new. Here are a list of things that I think we would want to get into a 5.1 release (not including the stuff in the [milestone](https://github.com/videojs/video.js/milestones/v5.1.0)). @videojs/core-committers please comment here if there are other things that should be included.

* [x] Remove unhelpful isCrossOrigin test #2715
* [x] ~~Don't test against http://example.com/english.vtt #2720~~  Fix track tests and ignore empty properties in tracks #2744 
* [x] Remove Android/iOS tests #2739
* [x] Add browserify:dist Target #2741 
* [x] Fix captions sticking to bottom for webkit browsers. #2702 
* [x]  Fix sandbox example to work in Video.js 5 #2691 
* [x]  Fixed argument names in API docs #2714 
* [x]  Modal Dialog - WIP #2668 
* [x]  Minor modal dialog CSS tweak. #2756 
* [x]  Added Microsoft Caption Maker link #2618 
* [x]  Remove z-index on big play button #2639 
* [x]  URL to player API docs 404s #2685 
* [x]  Use all installed browsers for unit tests #2708 
* [x] Update videojs-fonts to 1.4.0 -- will probably be part of #2668
* [x]  Add canPlayType method to player #2709 
* [x]  Refactors defaults for vtt.js #2426
* [x]  Defer the implementation of select functions in the tech to source handlers if they provide them #2760 

### Waiting for updates
* [ ] Chrome and Opera fail to load subtitles and captions #2689

**Comment by nickygerritsen** [comment]
What about #2709 ?

**Comment by gkatsev** [comment]
@nickygerritsen yep, that sounds like a good one to have as well.

**Comment by chemoish** [comment]
@gkatsev Would it be possible to consider https://github.com/videojs/video.js/pull/2678?

**Comment by gkatsev** [comment]
@chemoish yes, though, I think it's unlikely to get into 5.1. Probably 5.2.

**Comment by misteroneill** [comment]
I opened #2754, which is similar to #2718, but more comprehensive and exposes more DOM methods (and adds a couple new ones).

**Comment by gkatsev** [comment]
Font 1.4.0 is now on the CDN as well.

**Comment by misteroneill** [comment]
I'm going to propose we wait on the exposure and addition of DOM methods for 5.2 to reduce distractions.

**Comment by gkatsev** [comment]
Sounds good to me, @misteroneill.

**Comment by richardbushell** [comment]
Is heff's Source Handler Options still scheduled for 5.1?
https://github.com/videojs/video.js/issues/2616

**Comment by gkatsev** [comment]
I think that we'll probably release 5.1 with what's above and then work quickly towards a 5.2 with stuff like #2616 and #2678.

**Comment by heff** [comment]
lgtm :)

**Comment by gkatsev** [comment]
Looks like #2689 will have to wait for a 5.1.1 release.

**Comment by gkatsev** [comment]
I published 5.1.0 to npm as `video.js@next` and to github. We'll take a look at #2689 and publish 5.1.1 and get that out as a latest release. Also, if people can grab 5.1.0 and give it a shot and report any issues, that'll be great as well.

```js
$ npm dist-tag ls video.js
latest: 5.0.2
next: 5.1.0
```
