### ISSUE TITLE
5.4.0 release proposal

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2882]
* [x] ~~Emulate HTMLTrackElement to enable load event. #2804~~
* [x] Add Player#reset function. #2880 
* [x] videojs-ie8 to 1.1.1 #2869 
* [x] Add Player#tech. #2883 
* [x] Replace multi-line comment with single line comments #2827 
* [x] added ability to release as @next from master #2894 
* [x] Do a nullcheck for cues in updateForTrack. Fixes #2870 #2896

**Comment by gkatsev** [comment]
#2804 will be dropped from this release as it's not complete yet, unfortunately.

**Comment by dmlap** [comment]
Did a review pass for all of them. Some comments on #2880.

**Comment by gkatsev** [comment]
Going to release in the morning or later today. Hopeful that we could get #2804 into this release with @chemoish's help.

**Comment by gkatsev** [comment]
It's out on npm under the `@next` tag. I think that https://github.com/videojs/video.js/pull/2899 will fix the changelog and github release issues.

**Comment by gkatsev** [comment]
And I think I've got everything working now and released as 5.4.3.

**Comment by gkatsev** [comment]
Published 5.4.4 to the CDN and updated it's tag on npm to latest.
