### ISSUE TITLE
5.4.5 release proposal

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#2919]
* [x] This adds touch and move listeners to the parent of volumeBar. #2638 
* [x] Width of buttons is 4em. So, left:4em; #2913 
* [x] updated sandbox to to use newer/working CDN #2917 
* [x] Children are an array and no longer an object #2908 
* [x] Example fix #2915

**Comment by gkatsev** [comment]
https://github.com/videojs/video.js/releases/tag/v5.4.5 and as `@next` on npm.

**Comment by gkatsev** [comment]
5.4.5 as been superceded by 5.4.6 which is now on the CDN and released as stable.
