### ISSUE TITLE
Add Audio/Video Track support to video.js

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#3137]
## Purpose
To extend the capabilities of video.js so that we can support multiple audio and video tracks much like we support multiple text tracks right now.

## Proposal
* Follow the embedded content specification to:
	* implement the sharing of common functionality between TextTracks, AudioTracks, and VideoTracks.
	* implement VideoTrack, VideoTrackList, and enumerations
	* implement AudioTrack, AudioTrackList, and enumerations
	* possibly implement HTMLSourceElement
* Add functionality to video.js to utilize the new track lists in api

## API Spec
The main portions of the API will be defined in accordance with [embedded content specification][a]
Integration with video.js with follow the current patterns that TextTrack has laid out where it makes sense.

## Acceptance Criteria Most Covered by #3173 
1. [x] Convert Current TextTrack functionality to use ES6 syntax - (#3130) 
1. [x] ~~move `tracks/text-track*` files into `tracks/text/text-track*` - (#3146)~~ Not Doing
1. [x] Convert text track related unit test to full es6 syntax - (#3148) 
1. [x] Move common functionality from TextTrackList so that it can be reused by other TracksLists (#3173)
1. [x] Move common functionality from TextTrack so that it can be reused by other Tracks (#3173)
1. [x] ~~Research and implement the [HTMLSourceElement][b] api if required~~ Not Doing
1. [x] Follow the [AudioTrack][1] specification and reuse existing functionality to create the following: (#3173) 
  - [x] [AudioTrack][1]
  - [x] [AudioTrackList][2]
  - [x] [AudioTrackEnum][3]
1. [x] Follow the [VideoTrack][4] specification and reuse existing functionality to create the following: (#3173)
  - [x] [VideoTrack][4]
  - [x] [VideoTrackList][5]
  - [x] [VideoTrackEnum][6]
1. [x] Add audioTracks getter to: (#3173)
  - [x] [player][7]
  - [x] [tech][8]
  - [x] [html5][9]
1. [x] Add videoTracks getter to player and tech (#3173)
  - [x] [player][7]
  - [x] [tech][8]
  - [x] [html5][9]

[a]: https://html.spec.whatwg.org/multipage/embedded-content.html
[b]: https://html.spec.whatwg.org/multipage/embedded-content.html#htmlsourceelement
[1]: https://html.spec.whatwg.org/multipage/embedded-content.html#audiotrack
[2]: https://html.spec.whatwg.org/multipage/embedded-content.html#audiotracklist
[3]: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-audiotrack-kind
[4]: https://html.spec.whatwg.org/multipage/embedded-content.html#videotrack
[5]: https://html.spec.whatwg.org/multipage/embedded-content.html#videotracklist
[6]: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-videotrack-kind
[7]: https://github.com/videojs/video.js/blob/master/src/js/player.js
[8]: https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js
[9]: https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js

**Comment by BrandonOCasey** [comment]
#3130 will finish the first step

**Comment by gkatsev** [comment]
It's interesting that in the DOM, AudioTrackList, VideoTrackList, and TextTrackList all extend from EventTarget directly instead of from a "TrackList" parent.
Also, the AudioTrack, VideoTrack, and TextTrack, all share the same base set properties of `id, kind, label, language`, so we could probably abstract that part out as well.
I'd be interested to see if there is a usecase for implementing our own custom HTMLSourceElement.
This sounds good to me.

**Comment by gkatsev** [comment]
Oh, just realized that you mentioned that we can pull TextTrack out into a shared Track. We probably should do that separately from the TextTrackList PR to make it easier to merge.

We should try and make each PR for this epic as small and self contained as possible so we could merge chunks one at a time and not fall into the trap we always do (like captions) where we have a massive PR out for 3 months before it gets merged.

**Comment by gkatsev** [comment]
One other thing to mention, each of these tests need accompanying tests, of course :)

**Comment by BrandonOCasey** [comment]
Updated the issue to separate TextTrack and TextTrackList common functionality

**Comment by BrandonOCasey** [comment]
added another task to move all of the tracks/text-track* files into tracks/text/text-track*

**Comment by BrandonOCasey** [comment]
added another task to convert remaining text-track unit test into full es6 syntax

**Comment by BrandonOCasey** [comment]
#3137 is now merged, I think this issue can be closed
