### ISSUE TITLE
jsdoc comments are out of date, and there is not a good way to build them

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#3630]
## Description

Right now several documentation issues exist throughout the project, (@event and @method being mixed is one such issue that came up in #3597). I think we need to add a way to generate the docs, go through places where they seem wrong (by looking at what is generated), and fix any and all issues we come up against. It would probably be a good idea to include the API documentation on the website as well.
## Tasks
- [ ] hook jsdoc into the current build system (use recent jsdoc updates from [generator-videojs-plugin](https://github.com/videojs/generator-videojs-plugin/commit/f1e62b92fd596be895826a9c9d7ebdfc75fc78f6) as reference )
- [ ] look at the generated documentation and fix issues that exist
- [ ] Add a way to deploy the API docs to the website

**Comment by gkatsev** [comment]
I'm going to close this as we updated all the docs and we're working on builds.
